/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package pl.fermich.lab

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        expect:
        1 == 1
    }
}
